### PR TITLE
QL 11 Glyph Support

### LINKED ISSUE #44: Add 10.6 Glyph Stats
With Manufactury Breached, there are now 10.9 items with 10.6 glyphs.
Would it be possible to add the glyphs to the calculation?

### PR DESCRIPTION
**Pull request by Xeio**
Resolves #44.

I could go either way on the tooltips for the glyph distribution buttons. I added them since I figured it might be confusing to why the buttons were disabled, but it ends up being a bit ugly (in code anyway) making a tooltip work on a disabled button.

### CODE REVIEW

**Comment by joakibj** [comment]
Great, I'll review this when I get home from work tonight.

**Comment by joakibj** [comment]
Thanks, great PR as usual and it works fine :)
Regarding #44, I closed the issue, but I just realized that it does not resolve the fixed item drops that have 10.6 glyphs. So I guess it should stay open to get Manufactory Breached items in later?

**Comment by joakibj** [comment]
Actually, found a little bug #52 which is fixed

**Comment by Xeio** [comment]
Ah, 10.6 glyphs are sort of a misnomer. We were mostly using that as a naming convention till there was some item data indicating otherwise.

They really are just QL11.

**Comment by joakibj** [comment]
Ah awesome :+1:

**Pull request merged**
