### PR TITLE
 Issue 13 (Shambala) Signet Support #47

### PR DESCRIPTION
**Pull request by Inkraja**

### CODE REVIEW

**Comment by Xeio** [comment]
Two minor things I missed earlier: 

* The "icon:" parameter, those names should have underscores, not dashes. Images don't display correctly currently
* Names should probably omit "Signet of" to follow the pattern for the existing signets, right now only those Shambala signets have that

Also, the numbers are off in the selects unit tests (since there were new signets added), though @joakibj  may be able to fix that after merging.

**Comment by Inkraja** [comment]
github this automation is stupid .... i didnt want all the new commits in the same PR.... :disappointed:

**Comment by Xeio** [comment]
git rebase

It's only bad if people find out how much you abuse it. ;)

**Comment by joakibj** [comment]
Thanks for the contribution, however could you solve the conflicts with the current develop branch? Best would be to merge joakibj:develop in to your own branch and fix the conflicts

**Comment by Inkraja** [comment]
done

**Comment by joakibj** [comment]
I'll merge it in and fix any issues myself, thanks :)

Updates go live as 1.13.0 soon

**Comment by joakibj** [comment]
Okay I went through and corrected most of the issues like wrong stat names "critical-raiting" instead of "critical-rating" and it seems to work fine now.

A couple of things:

* Many items have an elite and epic variant, this should be distinguished in drop-down like Item Name [Elite]
* All items with role weapon does not show in the drop-down, I don't believe this is currently supported. @Xeio can maybe help with this.

I'll release this build as-is now and look these two other issues later. (I'll make new issues for those that want to do them). Else they get done best-effort :smile: 

Thanks for the contributions again :+1:

**Pull request merged**
