### PR TITLE
Issue12

### PR DESCRIPTION
**Pull request by Xeio**
Added 10.6 and 10.7 quality items
Updated Black Bullion costs to match Issue 12
Added new Pantheon costs calculations for 10.6+ items
Basic unit tests

I'm hosting a build of this at http://tswcalc.azurewebsites.net/ to play around with if you want to see it in action. This is based on TestLive but the item values seem unlikely to change at this point.

Minor quibbles: Layout for currency could probably be improved (I'm bad at CSS). Also I'm thinking maybe some sort of checkbox to include Fuses/Astrals into the BB/Pantheon costs since those can now be purchased.

### CODE REVIEW

**Comment by joakibj** [comment]
This looks good thus far! Seen as Issue 12 has not been released yet and as I've understood, currency conversions are up for preview then there's no need to push this to production yet. So things can be improved meanwhile.

Couple of things:
Currency and astral fuse / criterion upgrade view looks fine. The whole site has a dated look, so no issues if things look a tad off. Maybe a clearer seperator could be warranted between the two elements. In addition to the BB icon looking a bit cropped, can be scaled down if it doesn't fit... unless it looks like that in-game, which would be awful :(

Having a checkbox whether to pay with currency or raid drops is a good idea.

Last thing I was wondering, the upgrade from 10.4 -> 10.5 costs a criterion upgrade and 10.5 -> 10.7 only costs BB and pantheon?

Let's use this PR to discuss any Issue 12 changes to tswcalc

**Comment by Xeio** [comment]
>Maybe a clearer seperator could be warranted between the two elements. 

Maybe, I'm bad at CSS so I make no guarantees. Though maybe a small header to the raid-drops along with the add-to-currency-costs-checkbox or something like that.

>unless it looks like that in-game, which would be awful :(

I'm not sure how to pull higher quality images from the game, those are just screenshots cropped and cleaned up a little.

The new Black Bullion icon is rectangular, so if I didn't just crop them both to 32x32 to fit the existing icons it might look better. But as for the Pantheons... eh... the icon just looks jaggy even in-game.

>Last thing I was wondering, the upgrade from 10.4 -> 10.5 costs a criterion upgrade and 10.5 -> 10.7 only costs BB and pantheon?

Correct. Only 10.5 requires the criterion. If I was a betting man, I'd lay some reasonable odds on 11.0 might require them again (or something similar), but that's baseless speculation.

**Comment by Xeio** [comment]
Issue 12 is released. Doesn't seem like anything has changed that I'm aware of.

I still don't really know how to get a better looking currency images out of the game.

**Comment by joakibj** [comment]
Alright, I'll merge and release this when I get home from work in a few hours

**Comment by joakibj** [comment]
1.6.0 and forum update posts will be going up in a few minutes. Thanks for the awesome contribution, I'm sure the TSW community will appreciate it. :+1:

**Pull request merged**
