### PR TITLE
Updated supernal toolkit costs

### PR DESCRIPTION
**Pull request by Xeio**
So they're apparently still tweaking costs a bit this time. They didn't change any gear costs/numbers between test and live last time... I swear. :P

### CODE REVIEW

**Comment by joakibj** [comment]
That's fine, Funcom has always been that. Suddenly balance straight in to the Live servers :)

I'd like to have a testcase covering 10.8 and 10.9 gear aswell, for both stats and bb/pantheon cost. Just like these: https://github.com/joakibj/tswcalc/blob/develop/test/summary.js#L253

Can do it myself but I am not quite sure what QL the supernal kits are required for... heh

**Comment by Xeio** [comment]
Superior Kit = 10.6, 10.7
Supernal Kit = 10.8-11.0

Note that the Supernal kits say they also require a "Supernal Upgrade" for the 11.0 level. That's what I'm assuming is the NM raid drop.

**Comment by joakibj** [comment]
Okay, just to get this right. 

Is the cost per tier? That is, one superior kit for 10.6 and one for 10.7 or one kit to get both 10.6 -> 10.7?

Then the same for 10.8 -> 10.9 ? (and eventually 11.0)

Is the cost for the kits included in the [weapon and talisman data sets](https://github.com/joakibj/tswcalc/blob/develop/src/javascript/data/tswcalc-data-costs.js) ?

Because they are not added in the [summary calculation](https://github.com/joakibj/tswcalc/blob/develop/src/javascript/tswcalc-summary.js#L59). Nor can I find reference to tswcalc.data.costs.item.superior_talisman_kit.bullion

**Comment by Xeio** [comment]
>Is the cost per tier? That is, one superior kit for 10.6 and one for 10.7 or one kit to get both 10.6 -> 10.7?

Yup.

>Is the cost for the kits included in the weapon and talisman data sets ?
>Because they are not added in the summary calculation. Nor can I find reference to tswcalc.data.costs.item.superior_talisman_kit.bullion

Ah, so this was me originally thinking about reworking the cost calculations so it would dynamically calculate rather than needing to hard code each level. I didn't really end up doing that though, so the toolkit costs are mostly superfluous data in the json I was using for reference (rather than having to re-open the game to look). You can remove them if you'd rather they not be there. The costs are already included in the running totals for each level.

**Comment by joakibj** [comment]
It's fine, we can just leave it there for reference :)
Right now modularizing item cost calculation has no value, since there's only a total summary, not per-slot summary. Depending on how far Funcom are going to take item progression, it might be worth adding such a feature. Since cost overview is important to plan what content you want to play with ingame.

**Comment by joakibj** [comment]
I'll release and deploy this when I get home from work today by the way, considering the change is Live.

**Comment by Xeio** [comment]
Er, it's not live (yet). Earlier I meant they changed it while it was on Test Live. They didn't actually make any item cost/power changes last time so I wasn't expecting them this time.

Apparently the whining on the test forums won out. :P

Probably another 2-3 weeks till this hits at least, given they just dropped the NM version of NY onto Test Live.

**Pull request merged**
