### PR TITLE
Dropdown support for non-custom items

### PR DESCRIPTION
**Pull request by Xeio**
Somewhat large change, as you may imagine. [Viewable here.](http://tswcalc.azurewebsites.net/)

Also, I'm still going back and forth on whether to give 10.9 items a separate dropdown option, or just have 10.4/10.9 enabled in QL. The latter is probably cleaner, but requires more code work than just this change.

Other minor notes/changes:

* Items now default to "DPS" rather than "None".
* Bullion/MoP costs no longer calculate for NY items (previously only WC were omitted), glyphs still included in costs as needed
* No new items implemented yet (only 10.9 NY minor talis have dropped... so far)
* Fully compatible with old build links

More pressing issue with the PR:

Currently PhantomJS will not pass any unit tests via command line. I fixed them all and tested in Chrome/Edge so there are no errors when viewed there, but they will not pass using grunt. Not quite sure why, originally I (accidentally) included a lambda which seems to be too modern for PhantomJS, but even after changing that back to a function declaration, it still fails.

### CODE REVIEW

**Comment by joakibj** [comment]
First impressions look great, I'll take a closer look after work and check out the unit test issue. But it won't hinder the merge.

If 10.9 NY minor talismans are available, users should be able to choose between 10.4 or 10.9. But that can come in a later patch.

**Comment by Xeio** [comment]
Actually, just reviewing the overall changes again this morning and noticed I actually added two lambdas, so I need to also remove the other one.

Tried it and that at least gets me to a further error. Apparently Array only recieved the .find() method somewhat recently...

So I may have to rewrite all those instances. (Booo, hiss, browser compatibility woes)

**Comment by Xeio** [comment]
Corrected, grunt now works again. I just added a polyfill for array.find.

**Comment by joakibj** [comment]
Excellent. Looks good, works fine and backward compatibility is kept. Merging.

**Comment by joakibj** [comment]
The patched app has been released as 1.12.0 and deployed, thanks :+1:

**Pull request merged**
