### PR TITLE
Skill level 11 base stat values

### PR DESCRIPTION
**Pull request by Xeio**

### CODE REVIEW

**Comment by joakibj** [comment]
Nice PR, thanks.

However, could you remove the ugly merge commits from it?

**Comment by Xeio** [comment]
Aaaa I made it worse.

**Comment by Xeio** [comment]
Hooray, I fixed it. I can almost pretend I actually understand Git.

**Comment by joakibj** [comment]
Awesome, thanks :+1: 

Learn something new every day. Patch 1.6.3 goes out in a few minutes

**Pull request merged**
